services:
  recodehive:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Prevents node_modules being overwritten by the mount
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 # THIS is the crucial change for hot-reload!
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
